---
- name: Install zsh
  pacman: name=zsh state=present

- name: Set zsh as default shell
  user: name={{user}} shell=/bin/zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: /home/{{user}}/.oh-my-zsh
  become: yes
  become_user: "{{user}}"

- name: Install Tmux Plugin Manager
  git: repo=https://github.com/tmux-plugins/tpm dest=/home/{{user}}/.tmux/plugins/tpm
  become: yes
  become_user: "{{user}}"

- name: Install TPM plugins
  shell: /home/{{user}}/.tmux/plugins/tpm/bin/install_plugins
  args:
    creates: /home/{{user}}/.tmux/plugins/tmux-colors-solarized
  become: yes
  become_user: "{{user}}"

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
  become: yes
  become_user: "{{user}}"

- name: Install Vundle plugins
  shell: vim +PluginInstall +qall
  args:
    creates: /home/{{user}}/.vim/bundle/syntastic
  become: yes
  become_user: "{{user}}"
